# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: true

r_packages:
  - covr

r:
  - oldrel
  - release
  - devel

env:
  - CODECOV_TOKEN=$CODECOV_TOKEN

after_success:
  - travis_wait 20 Rscript -e 'covr::codecov()'
