# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logrank_instance <- function(groupa, groupb, groupacensored, groupbcensored, onlyz) {
    .Call(`_goldilocks_logrank_instance`, groupa, groupb, groupacensored, groupbcensored, onlyz)
}

